image: node:latest

stages:
  - install
  - build
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
    - main
  timeout: 1h

pages:
  stage: deploy
  script:
    - mv dist public
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - main

