image: node:latest

stages:
  - install
  - build
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
    - master

pages:
  stage: deploy
  script:
    - mv dist public
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master

image: node:18

variables:
    PUBLIC_URL: / 

before_script:
  - npm install
pages:
  script:
    - npm run prod
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  rules:

    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH



