image: node:18

variables:
    PUBLIC_URL: / 

before_script:
  - npm install
pages:
  script:
    - npm run prod
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  rules:

    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    



