image: node:14

stages:
  - install
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
  only:
    - main
  timeout: 20 minutes

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
    - main
  timeout: 30 minutes

pages:
  stage: deploy
  script:
    - mv dist public
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - main

